=== jnt0rrente/geoquiz/xml/forml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.uniovi.es"
    xmlns="http://www.uniovi.es" elementFormDefault="qualified">

    <xs:element name="forml">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="header"/>
                <xs:element ref="body"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="header">
        <xs:complexType/>
            <xs:sequence>
                <xs:element name="title" type="xs:string"/>
                <xs:element name="description" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="body">
        <xs:complexType/>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="section"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="section">
        <xs:complexType/>
            <xs:choice>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="section"/>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="question"/>
            </xs:choice>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="question">
        <xs:complexType/>
            <xs:sequence>
                <xs:element minOccurs="4" maxOccurs="4" ref="option"/>
            </xs:sequence>
            <xs:attribute name="text" type="xs:string" use="required"/>
            <xs:attribute name="accepted" type="validAnswer" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="option">
        <xs:complexType/>
            <xs:attribute name="text" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element>
        <xs:simpleType name="validAnswerType">
            <xs:restriction base="xs:string">
                <xs:enumeration value="a"/>
                <xs:enumeration value="b"/>
                <xs:enumeration value="c"/>
                <xs:enumeration value="d"/>
            </xs:restriction>
        <xs:simpleType/>
    </xs:element>

</xs:schema>

=== jnt0rrente/geoquiz/xml/forml-validation.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE forml SYSTEM "forml.dtd">

<forml xmlns="http://www.uniovi.es"
	xsi:schemaLocation="http://www.uniovi.es forml.xsd" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <header>
        <title>Sample quiz</title>
        <description>This is an example questionnaire for the GeoQuiz website.</description>
    </header>
    <body>
        <section name="Section 1">
            <question text="Which is the best rock?" accepted="b">
                <option text="Granite"/>
                <option text="Feldspar"/>
                <option text="Birch"/>
                <option text="Clay"/>
            </question>
        </section>
        <section name="Extra points">
            <section name="Economic geology">
                <question text="When was the gold standard abandoned?" accepted="c">
                    <option text="1970"/>
                    <option text="2009"/>
                    <option text="1850"/>
                    <option text="1900"/>
                </question>
                <question text="When were rocks invented?" accepted="b">
                    <option text="0 AD"/>
                    <option text="2 AD"/>
                    <option text="135 BC"/>
                    <option text="90 BC"/>
                </question>
            </section>
            <section name="Mineralogy">
                <question text="How many rocks are there?" accepted="d">
                    <option text="3"/>
                    <option text="4"/>
                    <option text="5"/>
                    <option text="More than 5"/>
                </question>
            </section>
        </section>
    </body>
</forml>
